import { useRef, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Grid, TextField, Button } from '@components/.';
import { FormEvent } from 'react';
import { getAll } from '@server/data/getAll';
import { Serie } from '@types/serie';
import axios from 'axios';

const Home: NextPage = () => {
  const searchRef = useRef<HTMLInputElement | null>(null);
  const [result, setResult] = useState();
  const onSearch = async (e: FormEvent) => {
    e.preventDefault();

    const data = await axios.get('http://localhost:3000/api/v1/series');
    console.log(data);
  };

  return (
    <div>
      <Head>
        <title>Suske en Wiske API</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Grid container spacing={3}>
          <Grid item xs={12}>
            sdfsfds
          </Grid>
          <Grid item xs={3}>
            side
          </Grid>
          <Grid item xs={9}>
            <form onSubmit={onSearch}>
              <TextField inputRef={searchRef} />
              <Button type='submit'>Request</Button>
            </form>
          </Grid>
        </Grid>
      </main>
    </div>
  );
};

export default Home;
